spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          #  断言规则
          predicates:
            #  参数url=baidu的路由到uri
            - Query=url,baidu
        - id: qq_route
          uri: https://www.qq.com
          #  断言规则
          predicates:
            - Query=url,qq
        - id: admin_route
          # lb为 load balacne 负载均衡， 后面是服务名
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
# 前端项目，都带上api前缀, /**表示匹配所有
  application:
    name: mall-gateway

server:
  port: 88
